<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>ปุ่มล็อคอิน</description>
   <name>btn_login</name>
   <tag></tag>
   <elementGuidId>b6b06d6b-27df-413a-97bc-52ca409a4be5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
