<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>ปุ่มล็อคอิน</description>
   <name>btn_login</name>
   <tag></tag>
   <elementGuidId>553e019d-2b89-4ceb-b66b-b16b2d85cf33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
