<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>กรอกวันที่</description>
   <name>txt_input_date</name>
   <tag></tag>
   <elementGuidId>83d0594a-8580-4f74-a3b7-80c13797f698</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_comment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;txt_visit_date&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
